name: web_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  video_player: ^2.5.0
  just_audio: ^0.9.30
  youtube_player_flutter: ^8.1.1
  webview_flutter: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/chapter1/pictures/
    - assets/chapter2/pictures/
    - assets/chapters/
    - assets/1_part0.mp3
    - assets/video_test.mp4